version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: cimg/aws:2022.11
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy --template-file template.yml --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} --region us-east-1

  configure_infrastructure:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - add_ssh_keys:
          # You can get this ID in the section where you registered the SSH Key
          fingerprints: ["ad:9d:92:4b:95:24:77:07:5f:aa:65:db:20:75:8f:6e"]
      - run:
          name: Install Ansible
          command: |
            # install the dependencies needed for your playbook
            python -m pip install ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory main.yml < yes
workflows:
  my-workflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure
